spring.application.name=jobportal
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal
server.tomcat.max-http-form-post-size=50MB
server.tomcat.max-parameter-count=100000000
server.tomcat.max-part-count=100000000
server.tomcat.max-swallow-size=-1
server.servlet.session.persistent=false
spring.servlet.multipart.enabled=true
spring.devtools.restart.enabled=true
spring.servlet.multipart.resolve-lazily=true
